Update to OpenH264 2.3.0

diff --git a/debian/openh264.postinst b/debian/openh264.postinst
--- a/debian/openh264.postinst
+++ b/debian/openh264.postinst
@@ -8,18 +8,22 @@
 # Bash options for strict error checking
 set -o errexit -o nounset
 
-OPENH264_VERSION="1.8.0"
+# Find the complete list of URLs in the project's Releases page:
+# https://github.com/cisco/openh264/releases
+#
+# Example URL:
+# http://ciscobinary.openh264.org/libopenh264-2.3.0-linux64.6.so.bz2
 OPENH264_SERVER="http://ciscobinary.openh264.org"
+OPENH264_VERSION="2.3.0"
+LIB_VERSION="6"
+DOWNLOAD_SHA256="a6294cde9ae10966cc639481b5c39b7fc57b2fcad417f11d7baca3b0f7914985"
 
-LIB_VERSION="4"
+DOWNLOAD_FILE="libopenh264-${OPENH264_VERSION}-linux64.${LIB_VERSION}.so.bz2"
 LIB_FILE="libopenh264-${OPENH264_VERSION}-linux64.${LIB_VERSION}.so"
 LIB_PATH="/usr/lib/x86_64-linux-gnu/libopenh264.so.${LIB_VERSION}"
 LIB_LINK="/usr/lib/x86_64-linux-gnu/libopenh264.so"
 
-BZ2_FILE="libopenh264-${OPENH264_VERSION}-linux64.${LIB_VERSION}.so.bz2"
-BZ2_HASH="0b879e4ba40df21b44c2531d343b6fb1f44b35176d4780ecb48dcab7f75f6779"
-
-[ -f "$BZ2_FILE" ] && rm "$BZ2_FILE"
+[ -f "$DOWNLOAD_FILE" ] && rm "$DOWNLOAD_FILE"
 [ -f "$LIB_FILE" ] && rm "$LIB_FILE"
 [ -f "$LIB_PATH" ] && { rm "$LIB_PATH"; rm "$LIB_LINK"; }
 
@@ -54,7 +58,7 @@ Redistribution and use in source and binary forms, with or without modification,
 
 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 
-THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 -----------------------------------------
 AVC/H.264 Patent Portfolio License Notice
@@ -62,7 +66,7 @@ AVC/H.264 Patent Portfolio License Notice
 
 The binary form of this Software is distributed by Cisco under the AVC/H.264 Patent Portfolio License from MPEG LA, and is subject to the following requirements, which may or may not be applicable to your use of this software:
 
-THIS PRODUCT IS LICENSED UNDER THE AVC PATENT PORTFOLIO LICENSE FOR THE PERSONAL USE OF A CONSUMER OR OTHER USES IN WHICH IT DOES NOT RECEIVE REMUNERATION TO (i) ENCODE VIDEO IN COMPLIANCE WITH THE AVC STANDARD ('AVC VIDEO') AND/OR (ii) DECODE AVC VIDEO THAT WAS ENCODED BY A CONSUMER ENGAGED IN A PERSONAL ACTIVITY AND/OR WAS OBTAINED FROM A VIDEO PROVIDER LICENSED TO PROVIDE AVC VIDEO.  NO LICENSE IS GRANTED OR SHALL BE IMPLIED FOR ANY OTHER USE.  ADDITIONAL INFORMATION MAY BE OBTAINED FROM MPEG LA, L.L.C. SEE HTTP://WWW.MPEGLA.COM
+THIS PRODUCT IS LICENSED UNDER THE AVC PATENT PORTFOLIO LICENSE FOR THE PERSONAL USE OF A CONSUMER OR OTHER USES IN WHICH IT DOES NOT RECEIVE REMUNERATION TO (i) ENCODE VIDEO IN COMPLIANCE WITH THE AVC STANDARD (“AVC VIDEO”) AND/OR (ii) DECODE AVC VIDEO THAT WAS ENCODED BY A CONSUMER ENGAGED IN A PERSONAL ACTIVITY AND/OR WAS OBTAINED FROM A VIDEO PROVIDER LICENSED TO PROVIDE AVC VIDEO.  NO LICENSE IS GRANTED OR SHALL BE IMPLIED FOR ANY OTHER USE.  ADDITIONAL INFORMATION MAY BE OBTAINED FROM MPEG LA, L.L.C. SEE HTTP://WWW.MPEGLA.COM
 
 Accordingly, please be advised that content providers and broadcasters using AVC/H.264 in their service may be required to obtain a separate use license from MPEG LA, referred to as \"(b) sublicenses\" in the SUMMARY OF AVC/H.264 LICENSE TERMS from MPEG LA found at http://www.openh264.org/mpegla
 
@@ -93,16 +97,16 @@ sleep 3
 
 echo "+ Download OpenH264 library from Cisco server"
 
-wget "${OPENH264_SERVER}/${BZ2_FILE}"
+wget "${OPENH264_SERVER}/${DOWNLOAD_FILE}"
 
-echo "+ Extract and install OpenH264 library"
-
-echo "$BZ2_HASH  $BZ2_FILE" | sha256sum --check >/dev/null 2>&1 || {
-    echo "SHA256 mismatch on $BZ2_FILE"
+echo "$DOWNLOAD_SHA256  $DOWNLOAD_FILE" | sha256sum --check >/dev/null 2>&1 || {
+    echo "SHA256 mismatch on $DOWNLOAD_FILE"
     exit 1
 }
 
-bzip2 --decompress --keep "$BZ2_FILE"
+echo "+ Extract and install OpenH264 library"
+
+bzip2 --decompress --keep "$DOWNLOAD_FILE"
 
 cp "$LIB_FILE" "$LIB_PATH"
 ln -s "$LIB_PATH" "$LIB_LINK"
@@ -110,8 +114,8 @@ ln -s "$LIB_PATH" "$LIB_LINK"
 echo "$LIB_PATH" >>/var/lib/dpkg/info/openh264.list
 echo "$LIB_LINK" >>/var/lib/dpkg/info/openh264.list
 
-# CleanupAS IS
-rm -f "$BZ2_FILE"
+# Cleanup
+rm -f "$DOWNLOAD_FILE"
 rm -f "$LIB_FILE"
 
 echo "libopenh264 ${LIB_VERSION} openh264" >>/var/lib/dpkg/info/openh264.shlibs
